# Generated by Django 3.1.7 on 2021-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
