# Generated by Django 3.1.7 on 2021-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0002_auto_20210328_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
